version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/deploy-scripts/
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: deploy-scripts/stop.sh
      runas: ec2-user
      timeout: 60

  BeforeInstall:
    - location: deploy-scripts/before_install.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: deploy-scripts/start.sh
      timeout: 120
      runas: ec2-user

  ValidateService:
    - location: deploy-scripts/validate.sh
      timeout: 60
      runas: ec2-user

