version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - chmod +x ./gradlew
      - chmod +x deploy-scripts/*.sh
      - ./gradlew --version
  build:
    commands:
      - ./gradlew clean build -x test

artifacts:
  files:
    - appspec.yml
    - deploy-scripts/**/*
    - build/libs/*.jar
  discard-paths: no